"""empty message

Revision ID: 641ed4969428
Revises: 18ba585b41ca
Create Date: 2020-02-13 17:59:13.131047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '641ed4969428'
down_revision = '18ba585b41ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_s_password', sa.String(length=256), nullable=True))
    op.drop_column('student', 's_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('student', '_s_password')
    # ### end Alembic commands ###
