"""empty message

Revision ID: 738fb2b08187
Revises: 
Create Date: 2020-02-12 23:17:47.533627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fb2b08187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_title', sa.String(length=32), nullable=True),
    sa.Column('n_content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
