"""empty message

Revision ID: e9f791ae137e
Revises: 641ed4969428
Create Date: 2020-02-13 18:32:47.852173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f791ae137e'
down_revision = '641ed4969428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_phone', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'student', ['s_phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 's_phone')
    # ### end Alembic commands ###
